export const CEB_MEMBER_SLUGS = [
  "federata-shqiptare-e-bilardos",
  "billard-sportverband-osterreich",
  "federation-royale-belge-de-billard",
  "croatian-billiard-association",
  "cyprus-carom-billiard-federation",
  "ceskomoravsky-billiardovy-svaz",
  "den-danske-billard-union",
  "suomen-biljardiliitto-ry",
  "federation-francaise-de-billard",
  "deutsche-billard-union",
  "eoaa-elliniki-omospondia-athlimaton-akriveias",
  "magyar-biliard-szovetseg",
  "federazione-italiana-sport-biliardo-e-bowling",
  "federation-luxembourgeoise-des-amateurs-de-billard",
  "koninklijke-nederlandse-biljartbond",
  "det-norske-biljardforbund",
  "federacao-portuguesa-de-bilhar",
  "real-federacion-espanola-de-billar",
  "federation-suisse-de-billard-carambole",
  "svenska-biljardforbundet",
  "turkiye-bilardo-federasyonu",
  "federazione-biliardo-sportivo-sammarinese",
] as const;

export const CEB_MEMBER_PIN_POSITIONS: Record<
  (typeof CEB_MEMBER_SLUGS)[number],
  { x: number; y: number }
> = {
  "federata-shqiptare-e-bilardos": { x: 56, y: 62 },
  "billard-sportverband-osterreich": { x: 47, y: 45 },
  "federation-royale-belge-de-billard": { x: 33, y: 35 },
  "croatian-billiard-association": { x: 52, y: 51 },
  "cyprus-carom-billiard-federation": { x: 73, y: 81 },
  "ceskomoravsky-billiardovy-svaz": { x: 46, y: 39 },
  "den-danske-billard-union": { x: 42, y: 22 },
  "suomen-biljardiliitto-ry": { x: 59, y: 12 },
  "federation-francaise-de-billard": { x: 29, y: 49 },
  "deutsche-billard-union": { x: 39, y: 35 },
  "eoaa-elliniki-omospondia-athlimaton-akriveias": { x: 60, y: 70 },
  "magyar-biliard-szovetseg": { x: 53, y: 44 },
  "federazione-italiana-sport-biliardo-e-bowling": { x: 44, y: 57 },
  "federation-luxembourgeoise-des-amateurs-de-billard": { x: 34, y: 39 },
  "koninklijke-nederlandse-biljartbond": { x: 33, y: 29 },
  "det-norske-biljardforbund": { x: 35, y: 12 },
  "federacao-portuguesa-de-bilhar": { x: 14, y: 55 },
  "real-federacion-espanola-de-billar": { x: 22, y: 60 },
  "federation-suisse-de-billard-carambole": { x: 37, y: 45 },
  "svenska-biljardforbundet": { x: 47, y: 14 },
  "turkiye-bilardo-federasyonu": { x: 72, y: 60 },
  "federazione-biliardo-sportivo-sammarinese": { x: 45, y: 54 },
};
