export const CEB_MEMBER_SLUGS = [
  "federata-shqiptare-e-bilardos",
  "billard-sportverband-osterreich",
  "federation-royale-belge-de-billard",
  "croatian-billiard-association",
  "cyprus-carom-billiard-federation",
  "ceskomoravsky-billiardovy-svaz",
  "den-danske-billard-union",
  "suomen-biljardiliitto-ry",
  "federation-francaise-de-billard",
  "deutsche-billard-union",
  "hellenic-federation-of-precision-sports",
  "magyar-biliard-szovetseg",
  "federazione-italiana-sport-biliardo-e-bowling",
  "federation-luxembourgeoise-des-amateurs-de-billard",
  "koninklijke-nederlandse-biljartbond",
  "det-norske-biljardforbund",
  "federacao-portuguesa-de-bilhar",
  "real-federacion-espanola-de-billar",
  "federation-suisse-de-billard-carambole",
  "svenska-biljardforbundet",
  "turkiye-bilardo-federasyonu",
  "federazione-biliardo-sportivo-sammarinese",
] as const;

export const CEB_MEMBER_PIN_POSITIONS: Record<
  (typeof CEB_MEMBER_SLUGS)[number],
  { x: number; y: number; offsetX?: number; offsetY?: number }
> = {
  "federata-shqiptare-e-bilardos": { x: 62.8, y: 88.4, offsetX: -8, offsetY: -2 },
  "billard-sportverband-osterreich": { x: 51.9, y: 77.9, offsetX: 8, offsetY: -16 },
  "federation-royale-belge-de-billard": { x: 40.3, y: 68.4, offsetX: -14, offsetY: -12 },
  "croatian-billiard-association": { x: 53.4, y: 80.2, offsetX: 16, offsetY: -8 },
  "cyprus-carom-billiard-federation": { x: 77.8, y: 100.8, offsetX: 8, offsetY: -4 },
  "ceskomoravsky-billiardovy-svaz": { x: 53.2, y: 70.9, offsetX: 10, offsetY: -8 },
  "den-danske-billard-union": { x: 49.7, y: 53.4, offsetX: -10, offsetY: -10 },
  "suomen-biljardiliitto-ry": { x: 68.8, y: 33.6, offsetX: 4, offsetY: -6 },
  "federation-francaise-de-billard": { x: 40.8, y: 76.1, offsetX: -20, offsetY: -4 },
  "deutsche-billard-union": { x: 49.4, y: 66.2, offsetX: -6, offsetY: -18 },
  "hellenic-federation-of-precision-sports": { x: 63.7, y: 91.8, offsetX: 6, offsetY: -12 },
  "magyar-biliard-szovetseg": { x: 58.2, y: 76.7, offsetX: 18, offsetY: -8 },
  "federazione-italiana-sport-biliardo-e-bowling": { x: 57.0, y: 90.0, offsetX: -14, offsetY: -6 },
  "federation-luxembourgeoise-des-amateurs-de-billard": { x: 48.8, y: 67.0, offsetX: -24, offsetY: 6 },
  "koninklijke-nederlandse-biljartbond": { x: 45.1, y: 62.8, offsetX: -16, offsetY: -12 },
  "det-norske-biljardforbund": { x: 47.2, y: 35.5, offsetX: -8, offsetY: -8 },
  "federacao-portuguesa-de-bilhar": { x: 24.7, y: 92.7, offsetX: -12, offsetY: -8 },
  "real-federacion-espanola-de-billar": { x: 32.5, y: 89.4, offsetX: -10, offsetY: 0 },
  "federation-suisse-de-billard-carambole": { x: 47.2, y: 77.4, offsetX: -4, offsetY: -4 },
  "svenska-biljardforbundet": { x: 54.6, y: 32.6, offsetX: 0, offsetY: -10 },
  "turkiye-bilardo-federasyonu": { x: 81.0, y: 93.1, offsetX: 12, offsetY: -10 },
  "federazione-biliardo-sportivo-sammarinese": { x: 50.2, y: 81.0, offsetX: 12, offsetY: 4 },
};
