export const CEB_MEMBER_SLUGS = [
  "federata-shqiptare-e-bilardos",
  "billard-sportverband-osterreich",
  "federation-royale-belge-de-billard",
  "croatian-billiard-association",
  "cyprus-carom-billiard-federation",
  "ceskomoravsky-billiardovy-svaz",
  "den-danske-billard-union",
  "suomen-biljardiliitto-ry",
  "federation-francaise-de-billard",
  "deutsche-billard-union",
  "eoaa-elliniki-omospondia-athlimaton-akriveias",
  "magyar-biliard-szovetseg",
  "federazione-italiana-sport-biliardo-e-bowling",
  "federation-luxembourgeoise-des-amateurs-de-billard",
  "koninklijke-nederlandse-biljartbond",
  "det-norske-biljardforbund",
  "federacao-portuguesa-de-bilhar",
  "real-federacion-espanola-de-billar",
  "federation-suisse-de-billard-carambole",
  "svenska-biljardforbundet",
  "turkiye-bilardo-federasyonu",
  "federazione-biliardo-sportivo-sammarinese",
] as const;

export const CEB_MEMBER_PIN_POSITIONS: Record<
  (typeof CEB_MEMBER_SLUGS)[number],
  { x: number; y: number }
> = {
  "federata-shqiptare-e-bilardos": { x: 60.5, y: 68.5 },
  "billard-sportverband-osterreich": { x: 48.8, y: 54.3 },
  "federation-royale-belge-de-billard": { x: 35.2, y: 42.6 },
  "croatian-billiard-association": { x: 53.8, y: 59.2 },
  "cyprus-carom-billiard-federation": { x: 72.8, y: 83.5 },
  "ceskomoravsky-billiardovy-svaz": { x: 47.8, y: 47.1 },
  "den-danske-billard-union": { x: 39.5, y: 31.2 },
  "suomen-biljardiliitto-ry": { x: 58.5, y: 22.4 },
  "federation-francaise-de-billard": { x: 28.6, y: 57.4 },
  "deutsche-billard-union": { x: 39.6, y: 45.8 },
  "eoaa-elliniki-omospondia-athlimaton-akriveias": { x: 60.8, y: 74.6 },
  "magyar-biliard-szovetseg": { x: 54.2, y: 56.4 },
  "federazione-italiana-sport-biliardo-e-bowling": { x: 45.9, y: 66.6 },
  "federation-luxembourgeoise-des-amateurs-de-billard": { x: 34.6, y: 45.8 },
  "koninklijke-nederlandse-biljartbond": { x: 34.5, y: 39.3 },
  "det-norske-biljardforbund": { x: 43.5, y: 20.6 },
  "federacao-portuguesa-de-bilhar": { x: 16.3, y: 70.3 },
  "real-federacion-espanola-de-billar": { x: 23.9, y: 68.5 },
  "federation-suisse-de-billard-carambole": { x: 39.9, y: 54.1 },
  "svenska-biljardforbundet": { x: 50.5, y: 25.4 },
  "turkiye-bilardo-federasyonu": { x: 71.2, y: 76.2 },
  "federazione-biliardo-sportivo-sammarinese": { x: 44.8, y: 63.8 },
};
