export type LiveScoreState = {
  scoreA?: number;
  scoreB?: number;
  runA?: number;
  runB?: number;
  liveRunA?: number;
  liveRunB?: number;
  current?: "A" | "B";
  inningsA?: number;
  inningsB?: number;
  inningsCount?: number;
  bestRunA?: number;
  bestRunB?: number;
  playerAName?: string;
  playerBName?: string;
  playerACountry?: string | null;
  playerBCountry?: string | null;
  playerAPhotoUrl?: string | null;
  playerBPhotoUrl?: string | null;
  playerAPhotoMainUrl?: string | null;
  playerBPhotoMainUrl?: string | null;
  progress?: number;
  totalBlocks?: number;
  isRunning?: boolean;
  timeoutsA?: number;
  timeoutsB?: number;
  maxTimeoutsA?: number;
  maxTimeoutsB?: number;
  avgFormattedA?: string;
  avgFormattedB?: string;
  accPercentA?: number;
  accPercentB?: number;
  playerATimeSeconds?: number;
  playerBTimeSeconds?: number;
  secondsPerInningA?: number;
  secondsPerInningB?: number;
  targetPointsA?: number | null;
  targetPointsB?: number | null;
  gameDurationSeconds?: number;
  inningsDetail?: Array<{
    inning: number;
    player1?: { pt: number; tot: number };
    player2?: { pt: number; tot: number };
  }>;
  tournamentName?: string | null;
  stageName?: string | null;
  groupName?: string | null;
  tableName?: string | null;
};

export type LiveSessionItem = {
  id: string;
  sessionId: string;
  screenId?: string | null;
  updatedAt?: string | null;
  clubId?: string | null;
  clubName?: string | null;
  clubCity?: string | null;
  clubFederationName?: string | null;
  state: LiveScoreState;
};
